CREATE DATABASE ALX_PORTFOLIO
USE ALX_PORTFOLIO

--FOR CUSTOMER INFO
CREATE TABLE CUSTOMER(
CUSTID INT PRIMARY KEY IDENTITY,
CUST_NAME VARCHAR(20),
CUST_PHONE VARCHAR(20),
CUST_EMAIL VARCHAR(40),
CUST_COUNTRY VARCHAR(15),
CUST_CITY VARCHAR(25),
CUST_REGION VARCHAR(25)
--CUST_NATIONALID --IDK HOW TO BCHA SCAN TEDERGO MIGEBA NW
);
DROP TABLE CUSTOMER
CREATE TABLE BOOKS_INFO(
BOOKID INT PRIMARY KEY IDENTITY,
AUTHOR_NAME VARCHAR(20),
DOP VARCHAR(10)
);
--REQUEST INFO
CREATE TABLE REQUEST_INFO(
REQID INT,
REQ_DATE DATE,
RETURN_DATE DATE
--ID SCAN
FOREIGN KEY(REQID) REFERENCES CUSTOMER(CUSTID)
);
SELECT * FROM REQUEST_INFO
DROP TABLE REQUEST_INFO

CREATE TABLE PREMIUM_USER(
PREMIUM INT PRIMARY KEY,
PID INT,
FOREIGN KEY(PID) REFERENCES CUSTOMER(CUSTID),
);
DROP TABLE PREMIUM_USER

CREATE TABLE MYSHELF(
MID INT,
FOREIGN KEY(MID) REFERENCES BOOKS_INFO(BOOKID),
FOREIGN KEY(MID) REFERENCES CUSTOMER(CUSTID),
FOREIGN KEY(MID) REFERENCES PREMIUM_USER(PREMIUM)
);
DROP TABLE MYSHELF
